-
  branches:
      only:
        - develop
  version: 1.0.{build}
  image: Visual Studio 2017
  environment:
    ANDROID_HOME: "C:\\android-sdk-windows"
    NUGET_SOURCE: https://www.myget.org/F/mvvmcross/api/v2/package
    NUGET_APIKEY:
      secure: m3uewWCh6Y5jqTZIfwMDfs8GWdbwTZjfiEl13AWY7T3u3bPspGA/lgwe8jdxjBm9
  init:
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip  
  - 7z x android-sdk_r24.4.1-windows.zip > nul
  - cd "C:\projects\MvvmCross"
  install:  
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-24.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-24
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository
  build_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - copy nuget.exe c:\Tools\NuGet /y
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'
  - ps: .\build.ps1
  test: off
  on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
